### ISSUE TITLE
Membership request webpart couldn't be placed in subsite

### ISSUE THREAD

**Issue by Mystikal57** [Visigo/SharePointFBAPack#170]
Hello,

I the Membership request webpart is placed in subsite, it search for Site Membership Review List in the subsite which doesn't exist.
https://url/subsite/Site Membership Review List

It should be here:
https://url/Site Membership Review List

thank you

**Comment by ccoulson** [comment]
Although sub site users can have unique permissions, in SharePoint the user profiles are stored at the site collection level - so the membership review list is at the site collection level.  You can't have users only available in a specific sub site - so if you use the membership request web part on a sub site, any users created there will also be available in all sub sites in the site collection.  (And actually the membership provider is at the Web Application level, so really that user will be able to login to all Site Collections in the same Web Application).

**Comment by Mystikal57** [comment]
This is not the problem..
I just want to have a registration form in a subsitepage, this isn't Working because thé Webpart search for site url and not root site url

**Comment by ccoulson** [comment]
I just retested using a registration web part on a sub site and I didn't have any issues.  You'll have to provide more details.

**Comment by Mystikal57** [comment]
hi, I don't know why it doesn't work for me...

An unexpected error has occurred. Please contact your administrator if this problem persists, or check the SharePoint log file for more details.
--

**Comment by ccoulson** [comment]
What does the SharePoint log file say? It should have more details.
