### ISSUE TITLE
visigo sharepoint fba pack automatically sends multiple spam emails

### ISSUE THREAD

**Issue by sandanet** [Visigo/SharePointFBAPack#174]
why the visigo sharepoint fba pack automatically sends multiple spam emails?
![spam](https://user-images.githubusercontent.com/33779375/186157804-1305ab11-7989-4a58-a64d-0d935e8a7808.png)

**Comment by ccoulson** [comment]
The FBA Pack does not automatically send any emails.  It does send emails when users perform certain actions, such as registering or requesting a password reset.  It also allows a custom email to be written by an administrator when they manually create a new account.  But the FBA Pack will not be automatically sending these emails.

**Comment by sandanet** [comment]
Thanks for the clarification
